### ISSUE TITLE
播放完成之后重新播放

### ISSUE THREAD

**Issue by wxiaofan** [seagazer/liteplayer#2]
播放完成之后手动重新播放如何实现

**Comment by seagazer** [comment]
重新设置一遍资源再启动播放就好了

**Comment by DamonXiong** [comment]
非循环模式，第一次播放完成后，控制栏按钮显示为暂停状态，点击中间的播放按钮没有反应，需要重新播放视频，这个如果操作？

**Comment by seagazer** [comment]
> 非循环模式，第一次播放完成后，控制栏按钮显示为暂停状态，点击中间的播放按钮没有反应，需要重新播放视频，这个如果操作？

不是太明白你的意思，直接重新调用start能满足你的场景吗

**Comment by DamonXiong** [comment]
> > 非循环模式，第一次播放完成后，控制栏按钮显示为暂停状态，点击中间的播放按钮没有反应，需要重新播放视频，这个如果操作？
> 
> 不是太明白你的意思，直接重新调用start能满足你的场景吗

我在On Complete回调中重新setDataSource，然后点击播放完成显示的那个播放按钮可以重新播放了。组件没有那种播放完成点击显示的播放按钮重新播放的功能，只能这样重新设置DataSource吗？

**Comment by seagazer** [comment]
> > > 非循环模式，第一次播放完成后，控制栏按钮显示为暂停状态，点击中间的播放按钮没有反应，需要重新播放视频，这个如果操作？
> > 
> > 
> > 不是太明白你的意思，直接重新调用start能满足你的场景吗
> 
> 我在On Complete回调中重新setDataSource，然后点击播放完成显示的那个播放按钮可以重新播放了。组件没有那种播放完成点击显示的播放按钮重新播放的功能，只能这样重新设置DataSource吗？

恩，从功能设计上的确是需要这样调用，如果是很多这种场景，建议你可以自定义一个overlay进行复用

**Comment by DamonXiong** [comment]
> > > > 非循环模式，第一次播放完成后，控制栏按钮显示为暂停状态，点击中间的播放按钮没有反应，需要重新播放视频，这个如果操作？
> > > 
> > > 
> > > 不是太明白你的意思，直接重新调用start能满足你的场景吗
> > 
> > 
> > 我在On Complete回调中重新setDataSource，然后点击播放完成显示的那个播放按钮可以重新播放了。组件没有那种播放完成点击显示的播放按钮重新播放的功能，只能这样重新设置DataSource吗？
> 
> 恩，从功能设计上的确是需要这样调用，如果是很多这种场景，建议你可以自定义一个overlay进行复用

了解了，谢谢。
